### ISSUE TITLE
How to scroll up when text goes down keyboard

### ISSUE THREAD

**Issue by RajChanchal** [hons82/THNotesTextView#1]
Hi there,
Thanks for the component, it's awesome. It needed to know how to move up text when a user is typing and he exceeds the keyboard. Now text goes behind the keyboard and we are unable to scroll too.

**Comment by hons82** [comment]
Hey!
Actually I use it in an iPad APP, so I move the whole (modal) view controller out of the way and didn't even notice that. I put a fix now in this version that should do the trick.
If you have tried it let me know if it works 4 u

**Comment by RajChanchal** [comment]
You are awesome!! Thanks a lot it worked for me! Don't mind, I think you forgot to correct it bit for iOS8, because there is a text suggestion bar too. For now, I just hidden the suggestion bar and your recent commit is working awesome. Thumbs up!
