### ISSUE TITLE
When NotesTextView was created custom input text is bad.

### ISSUE THREAD

**Issue by ALychkovsky** [hons82/THNotesTextView#2]
Hi, developers!
I really want to use yours lib, but when I programmatically create instance and add as subview notes text view then input text is bad display.

See example please: http://gyazo.com/730f88293c5c1d46a99872b96df1754f

Sorry for my bad English.

**Comment by RajChanchal** [comment]
Hi Alychkovsky, 
I was also having this problem, so I have used this one: https://github.com/kgn/KGNotePad

**Comment by RajChanchal** [comment]
Meanwhile the developer checks it out, you may try this one: https://github.com/kgn/KGNotePad
And can you tell me specifically (may be with screenshots of storyboards etc.) what were you doing?

**Comment by hons82** [comment]
Hi,
I'm currently not able to reproduce that behaviour. 
Could you send me how you instantiate it?

~hons
